# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: ashi-secure-os
description: A completely hermetic, terminal-free, secure study system.
base-image: ghcr.io/blue-build/base-images/fedora-kinoite
image-version: 40

modules:
  - type: script
    scripts:
      - install-zayit.sh

  - type: rpm-ostree
    install:
      - fsearch
      - onlyoffice-desktopeditors
      - sayonara
    remove:
      - firefox
      - sudo
      - konsole
      - elisa-player
      - dragon
      - kinfocenter
      - kernel-modules-extra

  - type: script
    scripts:
      - hermetic-lock.sh
      - create-shortcut.sh
