name: Build Vanilla OS ISO
on:
  workflow_dispatch: # הפעלה ידנית בלשונית Actions
  push:
    branches: [ main ]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Image with Vib
        # שימוש ב-Action הרשמי של ונילה
        uses: Vanilla-OS/vib-action@v1
        with:
          recipe: 'recipe.yml'
          tag: 'torah-os:latest'

      - name: Generate ISO
        # שימוש ב-Constructor הרשמי של ונילה
        uses: Vanilla-OS/os-constructor-action@v1
        with:
          image: 'torah-os:latest'

      - name: Upload ISO
        uses: actions/upload-artifact@v4
        with:
          name: Torah-OS-ISO
          path: ./*.iso
